crm_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projectcrm import views
from . import views
from django.urls import reverse
##import views from accounts
from accounts import views as accountview

urlpatterns = [
	url(r'^$', views.view_profile.as_view(), name = 'view_profile'),
	url(r'^tickets/details/$', views.ticket_detail.as_view(), name='ticket_detail'),
	url(r'^tickets/new-entry/$', views.new_entry, name='new_entry'),
    url(r'^new-ticket/$', views.create_ticket, name='create_ticket'),
    url(r'^tickets/$', views.tickets, name='tickets'),
    url(r'ajax_req/$', views.ajax_req, name='ajax_req'),
    url(r'^ajax/$', views.TicketFilter, name='ticket-filter'),
    url(r'^ticketform/$', views.ajax_form, name='ajax-form'),



    url(r'^client/$', views.ClientGet.as_view(), name='client'),
    url(r'^clientq/$', views.ClientPostQ.as_view(), name = 'client_detail'),
    url(r'^client_tech/$', views.ClientGetTech.as_view(), name = 'client_tech'),
    url(r'^client_tickets/$', views.ClientPostTickets.as_view(), name = 'client_tickets'),

    #url(r'^clienttest/$',  views.clienttest.as_view(), name = "clienttest"),	
    #url(r'^clientposttest/$',  views.clientposttest.as_view(), name = "clientposttest"),
    



]

projectcrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projectcrm import views
from django.urls import reverse

urlpatterns = [
	url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
    url(r'^crm/', include('crm_app.urls', namespace='crm'))
]
###crm namespace should be changed to something more unique.

crm_app/forms.py
from django import forms
from django.forms import ModelForm, modelform_factory, ModelChoiceField
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import *
from crm_app.models import *
from datetime import *
import time
from bootstrap3_datetime.widgets import DateTimePicker
from django_unixdatetimefield import UnixDateTimeField
from django.utils.dateformat import format



class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email', 
			'password1',
			'password2',
		)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user 




class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			'password'
		)

##Do I need this?
class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj 
##working function
## ticks = serviceticket.timestamp
## datetime(1,1,1) + timedelta(microseconds = ticks/10)
## output should be datetime.datetime(year, month, day, hour, minute, second ...etc)
#def testtime(*args, **kwargs):
#	dotnet = datetime(1,1,1)
#	times = datetime.now()
#	unix = times - dotnet
#	dotnettimestamp = (((unix.days*60*60*24 + unix.seconds)*1000 + unix.microseconds)*100)*100
#	return dotnettimestamp
from netunix import views
def movie():
	t = views.dotnet_unix().now()
	i = views.dotnet_unix().from_dotnet(t)
	m = datetime.fromtimestamp(i)
	return t

class NewTicketForm(forms.ModelForm):

	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title'}),
			'contact_name':forms.Select(),
			
		}
	#ticketstartdate = forms.DateField()
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.CharField()
	timestamp = forms.CharField(widget=forms.DateInput(attrs={"placeholder":movie, "value":movie}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))



class NewTicketTimeEntries(forms.ModelForm):
	class Meta:
		model = Timeentries
		fields = ("__all__")
		widgets = {
					'notes':forms.TextInput(attrs={'placeholder':'Entry Notes'}),
					'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),

		}

	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":"timestamp", "value":movie})) 
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype'))) 
	startdate = forms.DateTimeField(widget=forms.TextInput(attrs={"class":"datepicker"}))
	enddate = forms.DateTimeField(widget=forms.TextInput(attrs={"class":"datepicker"}))
	
		
		

###works when testtime funtion in here and timestamp value is set to time. Need to figure out how to get time to update when a new instance is called and not
###when code is saved and server restarted. 
class testticket(forms.ModelForm):

	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title'}),
			'contact_name':forms.TextInput(attrs={'placeholder':'contact'}),
			
		}
	
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.DateTimeField(widget=forms.HiddenInput())
	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":'timestamp', "value":movie}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))


class emailTest(forms.Form):
		subject = forms.CharField(required = True)	
		from_email = forms.EmailField(required=True)		
		message = forms.CharField()
		



	



		
		 
    
		

crm_app/views.py
from django.shortcuts import render, redirect
from django.db import connections, connection, models
from accounts.models import *
from crm_app.models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from crm_app.forms import *
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.forms import modelform_factory
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import F, Q
from django.views.generic import ListView, FormView, View, DetailView
from django.shortcuts import get_object_or_404



# Create your views here.
"""
def view_profile(request):
	if request.method == 'POST':
		if 'recent_tickets' in request.POST and request.POST['recent_tickets']:
			techname = request.POST['recent_tickets']
			tickets = Servicetickets.objects.filter(technician=techname).order_by('-ticketstartdate')
			lib={'user':request.user,'tickets':tickets}
			return render (request, 'crm_temps/view-profile.html', lib)
	else:		
		args = {'user': request.user}
		return render(request, 'crm_temps/view-profile.html', args)
"""




##class based view of view profile

'''
def ticket_detail(request):
	if request.method == "GET":
		if 'ticket' in request.GET and request.GET['ticket']:
			q= request.GET['ticket']
			qset = Servicetickets.objects.get(oid=q)
			tset = Timeentries.objects.filter(ticketid = q)
			lib = {'tickets':qset, 'entries':tset}
			return render(request, 'crm_temps/ticket-details.html', lib)
'''




def new_entry(request):
	if request.method == "GET":
		if 'editticket' in request.GET and request.GET['editticket']:
			req = request.GET['editticket']
			entry = NewTicketTimeEntries(request.GET)
			initialvalue = NewTicketTimeEntries(initial = {'ticketid':req})
			ticketreq = Servicetickets.objects.get(oid = req)
			timeentries = Timeentries.objects.filter(ticketid = req)
			lib = {'entries':entry, "tid":initialvalue, "ticket":ticketreq, "timeentries":timeentries}
			return render(request, 'crm_temps/forms/new-entry.html', lib)
	if request.method == "POST":
		entry = NewTicketTimeEntries(request.POST)
		if entry.is_valid():
			s = entry.save()
			return HttpResponse('saved')


def create_ticket(request):
	if request.method == "GET":
		ticket = NewTicketForm(request.GET)
		entries = NewTicketTimeEntries(request.GET)
		lib = {'ticket':ticket, 'entries':entries}
		return render(request, 'crm_temps/forms/new-ticket.html', lib)
		
	if request.method == "POST":
		ticket = NewTicketForm(request.POST)
		entries = NewTicketTimeEntries(request.POST)
		#subject = request.POST.get("ticket_title","")
		#message = request.POST.get("notes","")
		#from_email = request.POST.get("emailcomplete","")
		if ticket.is_valid() and entries.is_valid():
			m = ticket.save()
			entryintance = entries.instance
			k = m.timestamp
			ticket.save()
			v = Servicetickets.objects.get(timestamp = k)
			f = v.oid
			p = entryintance.ticketid
			entryintance.ticketid = f
			entries.save()
			
			#send_mail(subject, message, from_email, ['admin@example.com'])

			return HttpResponse(entryintance.ticketid)
		else:
			messages.error(request, "Error")
			return render(request, 'crm_temps/forms/new-ticket.html', {'ticket':ticket})


'''
def client(request):
	if request.method == "POST":
		if 'q' in request.POST and request.POST['q']: 
			q = request.POST['q']
			profile = Clientlist.objects.get(oid=q)
			contact = Contacts.objects.filter(clientid = q)
			 
			 
			lib= {'clientinfo':profile, 'contact':contact}
			return render(request, 'crm_temps/client_profile.html',lib)
		else:
			q = request.POST['tickets']
			tickets = Servicetickets.objects.filter(clientid=q).order_by("-timestamp")
			test = Clientlist.objects.get(oid=q)
			lib= {'tickets':tickets,
				  'name':test,
				  }

			return render(request, 'crm_temps/tickets.html',lib)
	elif request.method == "GET":
			if 'tech' in request.GET and request.GET['tech']:
				q = request.GET['tech']
				qset = Servicetickets.objects.filter(technician=q)
				lib = {'tickets': qset}
				return render(request, 'crm_temps/ticket-details.html', lib)
			else:
				query = Clientlist.objects.all().values()
				prnt = print(request)
				value = {'client': query}
				return render(request, 'crm_temps/client.html', value)
'''

###this could work, but need to render different templates for each request type.
'''
class client(ListView):
	#model = Clientlist
	#query_set = Clientlist.objects.all()
	#template_name = []
	#context_object_name = 'client'

	def get_context_data(self, **kwargs):
		context = super(client, self).get_context_data(**kwargs)
		if self.request.method == 'GET':
			if self.request.GET == 'tech':
				context['tickets'] = Servicetickets.objects.filter(technician = self.request.GET['tech'])
				return context
			else:
				context['client'] = Clientlist.objects.all().values()
				return context
		if self.request.method == "POST":
			if self.request.POST == 'q':
				context['clientinfo'] = Clientlist.objects.get(oid = self.request.POST['q'])
				context['contact'] = Contacts.objects.filter(clientid = self.request.POST['q'])
				return context
			if self.request.POST == 'tickets':
				context['tickets'] = Servicetickets.objects.filter(clientid = self.request.POST['tickets'])
				context['name'] = Clientlist.objects.get(oid = self.request.POST['tickets'])
				return context 

	def get_queryset(self):
		if self.queryset is None:
			if self.request.method == "GET":
				self.queryset = Clientlist.objects.all()
				return self.queryset
			if self.request.method == "POST":
				if 'q' in self.request.POST and self.request.POST['q']:
					self.queryset


	def post(self, request, *args, **kwargs):
		if self.request.method == "POST":
			self.object_list = self.get_queryset()
			allow_empty = self.get_allow_empty()
			context = self.get_context_data()
			return self.render_to_response(context)

	def get_template_names(self):
		self.template_name ='crm_temps/client.html'
		#template_name = super(client, self).get_template_names()
		req = self.request
		if req.method == "GET":
			template_name = 'crm_temps/client.html'
			return self.template_name
		if self.request.method == "POST":
			if 'q' in self.request.POST and self.request.POST['q']:
				self.template_name = 'crm_temps/client_profile.html'
				return super(client, self).get_template_names()


'''




'''
class client_detail(ListView):
	#query_set = Clientlist.objects.all()
	template_name = 'crm_temps/client_profile.html'
	context_object_name = "clientinfo"
	#extra_context = {'contact':Contacts.objects.all()}
	#query_set = Clientlist.objects.all()
	#model = Clientlist

	def get_context_data(self, **kwargs):
		context = super(clientposttest, self).get_context_data(**kwargs)
		context['contact'] =  Contacts.objects.filter(clientid = self.request.GET['q'])
		context['clientinfo'] = Clientlist.objects.get(oid = self.request.GET['q'])
		return context

	def get_queryset(self):
		if self.queryset is None:
			return self.queryset
'''





def tickets(request):
	if request.method == "GET":

		if 'cid' in request.GET and request.GET['cid']:
			q = request.GET['cid']
			tickets = Servicetickets.objects.filter(clientid=q)
			lib = {'tickets':tickets}
			return render(request, 'crm_temps/tickets.html', lib)
		elif 'tech' in request.GET and request.GET['tech']:
			q=request.GET['tech']
			tickets = Servicetickets.objects.filter(technician=q)
			lib = {'tickets':tickets}
			return render(request, 'crm_temps/tickets.html', lib)
		elif 'filter' in request.GET and request.GET['filter']:
			q = request.GET['filter']
			tickets = Servicetickets.objects.filter(ticket_status=1)
			lib={'tickets':tickets}
			return render(request, 'crm_temps/tickets.html')

		else:	
			tickets = Servicetickets.objects.all().order_by('-ticketstartdate')[:30]
			lib = {'tickets': tickets}
			return render(request, 'crm_temps/tickets.html', lib)

## Client Functions in CBV START HERE##
######################################
#####################################
####################################
class sdsdcreate_ticket(FormView):
	form_class = NewTicketForm
	success_url = '/'
	template_name = 'crm_temps/forms/new-ticket.html'
	initial = {'technician':'choose tech'}

	def get_context_data(self, *args, **kwargs):
		context = super(create_ticket, self).get_context_data(**kwargs)
		context['ticket'] = NewTicketForm(self.request.GET)
		context['entries'] = NewTicketTimeEntries(self.request.GET)
		return context
	def form_valid(self, form):
		if ticket.is_valid() and entries.is_valid():
			m = ticket.save()
			entryintance = entries.instance
			k = m.timestamp
			ticket.save()
			v = Servicetickets.objects.get(timestamp = k)
			f = v.oid
			p = entryintance.ticketid
			entryintance.ticketid = f
			entries.save()
			
			send_mail(subject, message, from_email, ['admin@example.com'])

			return HttpResponse(entryintance.ticketid)




class ClientMixin(object):
	"""Main mixin for client based functions. Change this before live. failed on get is an option so resubmitting
	a posted page will redirect to post it again"""
	failed_on_get = False
	def get_queryset(self, **kwargs):
		if self.queryset is None:
			return self.queryset

	def post(self, *args, **kwargs):
		if self.request.method == "POST" or self.failed_on_get == 'True':
			self.object_list = self.get_queryset()
			allow_empty = self.get_allow_empty()
			context = self.get_context_data()
			return self.render_to_response(context)

##vvvvvCBVs that Inherit from Client Mixin vvvvvvv###


#	def get_context_data(self, **kwargs):
#		context = super(tickets_cid, self).get_context_data(**kwargs)
#		context['cid']

class view_profile(ClientMixin, ListView):

	template_name = 'crm_temps/view-profile.html'
	context_object_name = 'placeholder'
	http_method_names = ['get','post']
	
	def get_context_data(self, **kwargs):

crm_app/templates/crm_temps/client.html
<form id='clientdetails_form' method = "POST" action="{% url 'crm:client_detail' %}">
	{% csrf_token %}
	  <ul class="collapsible">
	  	{% for client in client %}
    <li>
      <div class="collapsible-header" name='q' value="{{ client.oid }}"><i class="material-icons">swap_verticle_circle</i>{{ client.clientname }}</div>
      <div class="collapsible-body"></div>
    </li>
    {% endfor %}
    <input id='reqinput' type='hidden' name='' value=''>
  </ul>

</div>
</div> 
</div>
</form>
<style type="text/css">
	.client-collapse-header {
		font-size: 2.3rem;
	}
</style>
<script>
	  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
    $('.collapsible-header').click(function(){
    	reqName = $(this).attr('name');
    	reqValue = $(this).attr('value');
    	$('#reqinput').attr('name',reqName).attr('value', reqValue);
    	datastring = $('#clientdetails_form').serialize();
    	$.post($('#clientdetails_form').attr('action'), datastring, function(data){
    		$('.collapsible-body').html(data)
    	});
    })
   $("body:contains('')").children(function(){ 
          $(this).css("border","solid 2px red");
      
 });
</script>

        

crm_app/templates/crm_temps/client_profile.html
{% block body %}

		

<div class="container">
	<div class="container">
		<div class="row" id="title_row">
			<h1>{{ clientinfo.clientname }}</h1>
			<form method="GET" action="{% url 'crm:tickets' %}">				
				<button class="btn btn-default" type='submit' name="cid" value="{{ clientinfo.oid }}">View Service Tickets</button>
			</form>
			
		</div>
		<div class="row" id="adress_row">
			<h3>Address</h3>
				<h4>
				{{ clientinfo.address1 }} <br/>
				{{ clientinfo.address2 }}
				{{ clientinfo.address3 }}
				{{ clientinfo.city }},{{ clientinfo.state }} {{ clientinfo.zipcode }}
				</h4>
		</div>
		<div class="row" id="contactinfo_row">
			<h3>Contact Information</h3>
				<h4>
				{{ clientinfo.phonenumber }}, ext{{ clientinfo.extension }}<br/>			
				Primary Contact: {{ clientinfo.primarycontact }}<br/>
				Email: {{ clientinfo.email }}<br/>
				Fax Number: {{ clientinfo.fax_number }}<br/>
				{% for contact in contact %}
				{{ contact.contactname }}
				{% endfor %}
		</div>
				<table class='striped'>
			<thead>
				<th>Contact Name</th>
				<th>Phone Number</th>
				<th>Cell Phone</th>
				<th>Email</th>
				<th>Position</th>
			</thead>
			<tbody>
				{% for contact in contact %}
				<tr>
					<td>{{ contact.contactname }}</td>
					<td>{{ contact.phone_number }}</td>
					<td>{{ contact.cell_phone }}</td>
					<td>{{ contact.emailaddress }}</td>
					<td>{{ contact.title }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>



		<div class="row" id="clientinfo">
			<div class="row">
				<h3>Notes</h3>
			</div>				
				<h4>{{ clientinfo.notes }}<br/>
			<div class="row">
				<h3>Client Type</h3>
			</div>
				{{ type.type }}<br/>
			<div class="row">
				<h3>Do not Assist?</h3>
			</div>
			{{ clientinfo.donotassist|yesno:"Do not assist,Assist" }}<br/>
			</h4>			
		</div>
	</div>
</div>
{% endblock %}

crm_app/templates/crm_temps/navbar.html
<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
    <li><a href="{% url 'crm:create_ticket' %}">New Ticket</a></li>
    <li><a href="{% url 'crm:tickets' %}">Tickets</a></li>
    <li><a href="{% url 'crm:client' %}">Clients</a></li>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'crm:create_ticket' %}">Sass</a></li>
    <li><a href="{% url 'crm:tickets' %}">Components</a></li>
    <li><a href="{% url 'crm:client' %}">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>
  

  <script>
      $(document).ready(function(){
    $('.sidenav').sidenav();
  });
  </script>

crm_app/templates/crm_temps/printtest.html
printtest.html

crm_app/templates/crm_temps/ticket-details.html
{% extends 'base.html' %}

{% block body %}
<div class="row" id="status_row" style="background-color:lightgray;">
	<div class='col-sm-6'>
		<h3 style="display:inline;">{{ tickets.ticket_title }}</h3>
		<div class="status_class">
		<h3 style="display:inline;">Status:</h3>
		{% if tickets.ticket_status == 1 %}
		<h3 style="color:red; display:inline;">Call Recieved</h3>
		{% elif tickets.ticket_status == 2 %}
		<h3 style="color:yellow; display:inline;">In Progress</h3>
		{% elif tickets.ticket_status == 3 %}
		<h3 style="color:blue; display:inline;">Waiting Customer</h3>
		{% elif tickets.ticket_status == 4 %}
		<h3 style="color:blue; display:inline;">Waiting Vendor</h3>
		{% elif tickets.ticket_status == 5 %}
		<h3 style="color:green; display:inline;">Complete</h3>
		{% endif %}
	</div>
	</div>
</div>
<div class="row">
	<div class='col-sm-3'>
		<h4 class='ticket_header-field'>Ticket Start Date: </h4>
		<h4 class='ticket_header-field'>Ticket Initiated by: </h4>
		<h4 class='ticket_header-field'>Total Time spent: </h4>
		<h4 class='ticket_header-field'>Client: </h4>
		<h4 class='ticket_header-field'>Contact Name: </h4>
	</div>
	<div class='col-sm-3'>
		<h4>{{ tickets.ticketstartdate }}</h4>
		<h4>{{ tickets.technician }}</h4>
		<h4>{{ tickets.time_spent_minutes_field }} minutes</h4>
		<h4>{{ tickets.clientid }}</h4>
		<h4>{{ tickets.contact_name }}</h4>
	</div>
</div>








<h4>Ticket Entries</h4>

{% for entries in entries %}
<div class="container" id="entrycontainer">
{{ entries.startdate }} {{ entries.enddate }} <br/>
{{ entries.worktype }}<br/>
<h5 class="tech">{{ entries.technician }}<br/></h5>
{{ entries.notes }} <br />
</div>
{% endfor %}
<form method="GET" action="{% url 'crm:new_entry' %}">
	<button type="btn btn-default" value="{{ tickets.oid }}" name="editticket">Add New Time Entry</button>
</form>

<script>
	$('#entrycontainer > .tech').each(function(){
		var techname = $(this).text();
		if( techname == 'Mike') {
			$('#entrycontainer').attr('style','border-left:solid rgb(125,154,59,1) 10px');
		}
		if( techname == 'Ross') {
			$('#entrycontainer').attr('style','border-left:solid lightgrey 4px');
		}
		if( techname == 'Marcus') {
			$('#entrycontainer').attr('style','border-left:solid lightblue 4px');
		}
		if( techname == 'Aaron') {
			$('#entrycontainer').attr('style','border-left:solid maroon 4px');
		}
	});

</script>

{% endblock %}

crm_app/templates/crm_temps/tix.html
  <!--Base template for ticket table. Uses Ajax and Jquery to render -->	
	<form id='ff' method="GET" action="{% url 'crm:ticket_detail' %}" id="profile_tickets">



					<table class='striped responsive-table-vertical'>
						<caption>Active Issues</caption>
						<thead>
	          				<tr>
	          					<th>Technician</th>
	              				<th>Ticket Title</th>
	              				<th>Start Date</th>
	              				<th>Status</th>
	          				</tr>
	    				</thead>
	     				<tbody>	          			
	        			</tbody>
					</table>
				</form>


<script>
	$(document).ready(function(){
    $('.fixed-action-btn').floatingActionButton();
    
  });
</script>

crm_app/templates/crm_temps/view-profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
<form method="GET" action="{% url 'accounts:testemail' %}">
	<button type='submit'>TESTMAIL</button>
</form>
{% endblock %}

{% block title %}
<h3>Dashboard<h4>
{% endblock %}

{% block body %} 
{% if tickets %}


  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li id="currentissues" class="tab col s3"><a class="active" href="#test1">Current Issues</a></li>
        <li id="newticket" class="tab col s3"><a id="newtix" href="#test2">Start New Ticket</a></li>
        <li id="orders" class="tab col s3"><a href="#test3">View Orders and Invoices</a></li>
        <li id="contacts" class="tab col s3"><a href="#test4">Clients and Contacts</a></li>
      </ul>
    </div>
    <div id="test1" class="col s12"></div>
    <div id="test2" class="col s12"></div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div>
  </div>

<a id="ajaxUrl" href="{% url 'crm:ticket-filter' %}"></a>
<a id="ajax_url" href="{% url 'crm:ajax_req' %}"></a>
<a id="clients_url" href="{% url 'crm:client' %}"></a>
<a id="form_url" href="{% url 'crm:create_ticket' %}"></a>


{% else %}
<div class='container'>
<h2>username: {{ user }}</h2>
<h2>first name: {{ user.first_name }}</h2> 
<h2>last name: {{ user.last_name }}</h2>
<h2>email: {{ user.email }}</h2>
</div>
<form method="POST" action="" id="auto_submit_form">
	{% csrf_token %}
	<input type="hidden" name="recent_tickets" value="{{ user.username }}"></input>
</form>
{% endif %}
<style>
.current-issues-window {
	max-height: 50vh;
	max-width: 30vw;
	overflow-x: hidden;
	overflow-y: scroll;
	background-color: lightgray;
	float: right;
}
</style>
<script type="text/javascript">
	$(document).ready(function(){
		$('#newticket').click(function(){
			$.get($('#form_url').attr('href'), function(data){
				$('#test1').empty();
				$('#test2').html(data);
		});
	});

		$('#contacts').click(function(){
			$.get($('#clients_url').attr('href'), function(data){
				$('#test4').html(data);
			});
		});
///maybe add the filter is a form and include it in the templates

		$('#currentissues').click(function(){
			$.get($('#ajax_url').attr('href'), function(data){				
				$('#test1').html(data)
			})
		});
		$('.collapsible').collapsible();

	
	$("#auto_submit_form").submit();
	$('.tabs').tabs();
	$('.fixed-action-btn').floatingActionButton();
    $('.datepicker').datepicker();
    $('select').formSelect();

	});


///Try adding a function that executes the ajax call on the tix template. Then when the tab is clicked it will call the function??
//The easiest method may be to simply have types of ticket lists. 1- current tickets(everything in last 3 months) 2- 

		

	

</script>

{% endblock %}