crm_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projectcrm import views
from . import views
from django.urls import reverse
##import views from accounts
from accounts import views as accountview

urlpatterns = [
	url(r'^$', views.view_profile.as_view(), name = 'view_profile'),
	url(r'^tickets/details/$', views.ticket_detail.as_view(), name='ticket_detail'),
	url(r'^tickets/new-entry/$', views.new_entry, name='new_entry'),
    url(r'^new-ticket/$', views.create_ticket, name='create_ticket'),
    url(r'^tickets/$', views.tickets, name='tickets'),
    url(r'ajax_req/$', views.ajax_req, name='ajax_req'),
    url(r'^ajax/$', views.TicketFilter, name='ticket-filter'),
    url(r'^ticketform/$', views.ajax_form, name='ajax-form'),



    url(r'^client/$', views.ClientGet.as_view(), name='client'),
    url(r'^clientq/$', views.ClientPostQ.as_view(), name = 'client_detail'),
    url(r'^client_tech/$', views.ClientGetTech.as_view(), name = 'client_tech'),
    url(r'^client_tickets/$', views.ClientPostTickets.as_view(), name = 'client_tickets'),

    #url(r'^clienttest/$',  views.clienttest.as_view(), name = "clienttest"),	
    #url(r'^clientposttest/$',  views.clientposttest.as_view(), name = "clientposttest"),
    



]

projectcrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projectcrm import views
from django.urls import reverse

urlpatterns = [
	url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
    url(r'^crm/', include('crm_app.urls', namespace='crm'))
]
###crm namespace should be changed to something more unique.

crm_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django_unixdatetimefield import UnixDateTimeField

# Create your models here.
class Clientlist(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    clientname = models.CharField(db_column='ClientName', unique=True, max_length=255, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.
    techsupportplan = models.CharField(db_column='TechSupportPlan', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address1 = models.CharField(db_column='Address1', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address2 = models.CharField(db_column='Address2', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address3 = models.CharField(db_column='Address3', max_length=255, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=255, blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=255, blank=True, null=True)  # Field name made lowercase.
    zipcode = models.CharField(db_column='ZipCode', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phonenumber = models.CharField(db_column='PhoneNumber', max_length=255, blank=True, null=True)  # Field name made lowercase.
    extension = models.CharField(db_column='Extension', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fax_number = models.CharField(db_column='Fax Number', max_length=50, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    primarycontact = models.CharField(db_column='PrimaryContact', max_length=255, blank=True, null=True)  # Field name made lowercase.
    donotassist = models.NullBooleanField(db_column='DoNotAssist')  # Field name made lowercase.
    clienttype = models.IntegerField(db_column='ClientType', blank=True, null=True)  # Field name made lowercase.
    notes = models.TextField(db_column='Notes', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ClientList'


class Clientnotes(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID', blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=255, blank=True, null=True)  # Field name made lowercase.
    notes = models.TextField(db_column='Notes', blank=True, null=True)  # Field name made lowercase.
    category = models.IntegerField(db_column='Category', blank=True, null=True)  # Field name made lowercase.
    new_ticket_popup = models.CharField(db_column='New Ticket Popup', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'ClientNotes'


class Clienttypes(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=50, blank=True, null=True)  # Field name made lowercase.
    createtickets = models.NullBooleanField(db_column='CreateTickets')  # Field name made lowercase.
    defaultchecked = models.NullBooleanField(db_column='DefaultChecked')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ClientTypes'


class Companyinventory(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    itemid = models.IntegerField(db_column='ItemID')  # Field name made lowercase.
    typeid = models.IntegerField(db_column='TypeID', blank=True, null=True)  # Field name made lowercase.
    serialnumber = models.CharField(db_column='SerialNumber', max_length=255, blank=True, null=True)  # Field name made lowercase.
    datereceived = models.DateTimeField(db_column='DateReceived', blank=True, null=True)  # Field name made lowercase.
    dateinstalled = models.DateTimeField(db_column='DateInstalled', blank=True, null=True)  # Field name made lowercase.
    itemnotes = models.TextField(db_column='ItemNotes', blank=True, null=True)  # Field name made lowercase.
    currentclient = models.IntegerField(db_column='CurrentClient', blank=True, null=True)  # Field name made lowercase.
    billed = models.DateTimeField(db_column='Billed', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CompanyInventory'
        unique_together = (('oid', 'itemid'),)


class Companyinventorydetail(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    companyinventoryid = models.IntegerField(db_column='CompanyInventoryID', blank=True, null=True)  # Field name made lowercase.
    serviceticket = models.IntegerField(db_column='ServiceTicket', blank=True, null=True)  # Field name made lowercase.
    client = models.IntegerField(db_column='Client', blank=True, null=True)  # Field name made lowercase.
    workstart = models.DateTimeField(db_column='WorkStart', blank=True, null=True)  # Field name made lowercase.
    workstop = models.DateTimeField(db_column='WorkStop', blank=True, null=True)  # Field name made lowercase.
    detailnotes = models.TextField(db_column='DetailNotes', blank=True, null=True)  # Field name made lowercase.
    billable = models.NullBooleanField(db_column='Billable')  # Field name made lowercase.
    billed = models.NullBooleanField(db_column='Billed')  # Field name made lowercase.
    billableamount = models.DecimalField(db_column='BillableAmount', max_digits=19, decimal_places=4, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CompanyInventoryDetail'


class Contacts(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID', blank=True, null=True)  # Field name made lowercase.
    contactname = models.CharField(db_column='ContactName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=255, blank=True, null=True)  # Field name made lowercase.
    emailaddress = models.CharField(db_column='EmailAddress', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone_number = models.CharField(db_column='Phone Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    extension = models.CharField(db_column='Extension', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cell_phone = models.CharField(db_column='Cell Phone', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    notes = models.CharField(db_column='Notes', max_length=255, blank=True, null=True)  # Field name made lowercase.
    primary = models.NullBooleanField(db_column='Primary')  # Field name made lowercase.
    sendticketassignemail = models.NullBooleanField(db_column='SendTicketAssignEmail')  # Field name made lowercase.
    sendticketcompleteemail = models.NullBooleanField(db_column='SendTicketCompleteEmail')  # Field name made lowercase. 

    class Meta:
        managed = False
        db_table = 'Contacts'


class Internalemailaddresses(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    emailaddress = models.CharField(db_column='EmailAddress', max_length=255, blank=True, null=True)  # Field name made lowercase.
    smtphost = models.CharField(db_column='SmtpHost', max_length=255, blank=True, null=True)  # Field name made lowercase.
    smtpport = models.IntegerField(db_column='SmtpPort', blank=True, null=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'InternalEmailAddresses'


class Inventoryitems(models.Model):
    oid = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    itemname = models.CharField(db_column='ItemName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    model_number = models.CharField(db_column='Model Number', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    upc = models.CharField(db_column='UPC', max_length=255, blank=True, null=True)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
    currentinventoryitem = models.NullBooleanField(db_column='CurrentInventoryItem')  # Field name made lowercase.
    cost = models.DecimalField(db_column='Cost', max_digits=19, decimal_places=4, blank=True, null=True)  # Field name made lowercase.

crm_app/forms.py
from django import forms
from django.forms import ModelForm, modelform_factory, ModelChoiceField
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import *
from crm_app.models import *
from datetime import *
import time
from bootstrap3_datetime.widgets import DateTimePicker
from django_unixdatetimefield import UnixDateTimeField
from django.utils.dateformat import format



class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email', 
			'password1',
			'password2',
		)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user 




class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			'password'
		)

##Do I need this?
class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj 
##working function
## ticks = serviceticket.timestamp
## datetime(1,1,1) + timedelta(microseconds = ticks/10)
## output should be datetime.datetime(year, month, day, hour, minute, second ...etc)
#def testtime(*args, **kwargs):
#	dotnet = datetime(1,1,1)
#	times = datetime.now()
#	unix = times - dotnet
#	dotnettimestamp = (((unix.days*60*60*24 + unix.seconds)*1000 + unix.microseconds)*100)*100
#	return dotnettimestamp
from netunix import views
def movie():
	t = views.dotnet_unix().now()
	i = views.dotnet_unix().from_dotnet(t)
	m = datetime.fromtimestamp(i)
	return t

class NewTicketForm(forms.ModelForm):

	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title'}),
			'contact_name':forms.Select(),
			
		}
	#ticketstartdate = forms.DateField()
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.CharField()
	timestamp = forms.CharField(widget=forms.DateInput(attrs={"placeholder":movie, "value":movie}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))



class NewTicketTimeEntries(forms.ModelForm):
	class Meta:
		model = Timeentries
		fields = ("__all__")
		widgets = {
					'notes':forms.TextInput(attrs={'placeholder':'Entry Notes'}),
					'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),

		}

	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":"timestamp", "value":movie})) 
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype'))) 
	startdate = forms.DateTimeField(widget=forms.TextInput(attrs={"class":"datepicker"}))
	enddate = forms.DateTimeField(widget=forms.TextInput(attrs={"class":"datepicker"}))
	
		
		

###works when testtime funtion in here and timestamp value is set to time. Need to figure out how to get time to update when a new instance is called and not
###when code is saved and server restarted. 
class testticket(forms.ModelForm):

	class Meta:
		model = Servicetickets
		fields = ("__all__")
		widgets = {
			#'ticketstartdate':DateTimePicker(options={"format": "YYYY/MM/DD HH:mm:ss"}, attrs={'onchange':'this.form.submit()'}),
			'technician': forms.Select(choices=Technicians.objects.values_list('nickname','nickname')),
			'ticket_title':forms.TextInput(attrs={'placeholder':'title'}),
			'contact_name':forms.TextInput(attrs={'placeholder':'contact'}),
			
		}
	
	clientid = forms.IntegerField(widget=forms.Select(choices=Clientlist.objects.values_list('oid','clientname')
		))
	#technician = forms.CharField(widget=forms.Select(choices=Technicians.objects.values_list('nickname','nickname')))
	worktype = forms.CharField(widget=forms.Select(choices=Worktypes.objects.values_list('worktype', 'worktype')))
	ticketstartdate = forms.DateTimeField(widget=forms.HiddenInput())
	timestamp = forms.CharField(widget=forms.DateInput(attrs={
		"placeholder":'timestamp', "value":movie}))
	ticket_status = forms.CharField(widget=forms.Select(choices=Ticketstatuses.objects.values_list('oid','status')))


class emailTest(forms.Form):
		subject = forms.CharField(required = True)	
		from_email = forms.EmailField(required=True)		
		message = forms.CharField()
		



	



		
		 
    
		

crm_app/templates/crm_temps/forms/create-ticket.html
{% extends 'base.html' %}
{% block body %}
{% block title %}
<h3>New Ticket</h3>
<form method=POST action="{% url 'accounts:test' %}">
	{% csrf_token %}
	<div class="container">
  <div class="row">
    Date formats: yyyy-mm-dd, yyyymmdd, dd-mm-yyyy, dd/mm/yyyy, ddmmyyyyy
  </div>
  <br />
    <div class="row">
        <div class='col-sm-3'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input name='ticketstartdate" type='text' class="form-control">{{ ticket.ticketstartdate }}</input>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

 {{ ticket.timestamp }}
 {{ ticket.ticket_title }}
 {{ ticket.clientid }}
 {{ ticket.worktype }}
 {{ ticket.ticket_status }}
 {{ ticket.technician }}
 {{ ticket.contact_name }}

<button type='submit'>Submit</button>
<script>
	
</script>
</form>
{% endblock %}

crm_app/templates/crm_temps/forms/dropdown-filter.html
<ul class="collapsible">
    <li>
        <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
        <div class="collapsible-body">
            <form id='filter_form' method="GET" action="{% url 'crm:ticket-filter' %}">
                <div class="input-field col s12">
                    <select multiple name="tech_filter">
                        {% for technician in technician %}
                        <option value="{{ technician.nickname }}">{{ technician.nickname }}</option>
                        {% endfor %}
                    </select>
                    <label>Materialize Multiple Select</label>
                </div>

                <div class="input-field col s12">
                    <select multiple name="client_filter">
                        {% for client in client %}
                        <option value="{{ client.oid }}">{{ client.clientname }}</option>
                        {% endfor %}
                    </select>
                    <label>Materialize Multiple Select</label>
                </div>
                <div class="input-field col s12">
                    <select multiple name="status_filter">
                        {% for status in status %}
                        <option value="{{ status.oid }}">{{ status.status }}</option>
                        {% endfor %}
                    </select>

                    <label>Materialize Multiple Select</label>
                </div>

             
      
            </form>
        </div>
        </div>
    </li>
</ul>
<button id="tickettab">Filter</button>


<script type="text/javascript">
  $(document).ready(function(){
      $('.dropdown-trigger').dropdown();
       $('.collapsible').collapsible();
  });
</script>

crm_app/templates/crm_temps/forms/edit-ticket.html
{% extends 'base.html' %}

{% block body %}


<form method="POST" action="{%  url 'accounts:edit_ticket' %}">
 {{ ticket.ticket_title }}

 {% for timeentries in timeentries %}
 {{ timeentries.notes }}
 {% endfor %}

</form>
{% endblock %}

crm_app/templates/crm_temps/forms/entry-form.html
{% block entry-form %}
<form method=POST action="{% url 'crm:new_entry' %}">
    {% csrf_token %}
    
        <h4>for debugging</h4>
        {{ tid.ticketid }}
        {{ entries.timestamp }}
        
        <h2>Entry details</h2>
        <h5>Technician</h5>
        {{ entries.technician }}        
        <h5>Work Type</h5>
        {{ entries.worktype }}
        <h5>Notes</h5>
        {{ entries.notes }}
        <h5>Total Time Spent On Ticket</h5>    
        {{ ticket.time_spent_minutes_field }}
        
        {{ entries.startdate }}
   
        {{ entries.enddate }}

        <button class="datepicker">

        

        <button style="background-color:green; margin:5em;" class="btn btn-lg" type='submit'>Submit</button>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('select').formSelect();
        $('.datepicker').datepicker({
            autocClose: true,
        });

    });

</script>
{% endblock %}

crm_app/templates/crm_temps/forms/multi-page-new-ticket.html
{% block multi-page-new-ticket %}
<form method=POST action="{% url 'crm:create_ticket' %}" style='margin:1.5rem; box-shadow: -1px 3px 5px 1px grey;'>
    {% csrf_token %}
   {{ ticket.errors }}
   {{ entries.non_field_errors}}

<div class='v' style='border-bottom:solid grey 2px; margin: 1.5rem;'>

 <div class='row'>
    <div class='col l4 s12 '>
        <h6>Enter Title</h6>
    {{ ticket.ticket_title }}
    </div>
    <div class='col l4 offset-l4 s12'>
        <h6>Tech Name</h6>
    {{ ticket.technician }}
    </div>
 </div>


 <div class='row'>
    <div class='col l4 s12'>
        <h6>Ticket Start Date</h6>
    {{ ticket.ticketstartdate }}
    </div>
    <div class='col l4 offset-l4 s12'>
        <h6> Total Time Spent On Ticket</h6>
        {{ ticket.time_spent_minutes_field }}
    </div>
</div>
 <div class='row'>
    <div class='col l6 s12'>
        <h6>Client Name</h6>
    {{ ticket.clientid }}
    </div>
</div>
 <div class='row'>
    <div class='col l4 s12'>
        <h6>Contact Name</h6>
    {{ ticket.contact_name }}
    </div>
    <div class='col l4 offset-l4 s12'>
        <h6>Send Complete Email?</h6>
        <div id="hotness">
        </div>
    </div>
</div>
 <div class='row'>
    <div class='col l6 s12'>
        <h6>Ticket Status</h6>
    {{ ticket.ticket_status }}
    </div>
</div>
 <div class='row'>
    <div class='col l6 s12'>
        <h6>Client Notes</h6>
    {{ ticket.client_notes }}
    </div>
</div>
 <div class='row'>
    <div class='col l6 s12'>
        <h6>Worktype</h6>
    {{ ticket.worktype }}
    </div>
</div>
 <div class='row'>
    <div class='col l6 s12'>
        <h6>Internal Notes</h6>
    {{ ticket.internal_notes }}
    </div>
</div>
 <div class='row'>
    <div class='col l4 s12'>
    {{ ticket.oid }}
    </div>
        <div class='col l4 s12'>
    {{ ticket.timestamp }}
    </div>
        <div class='col l4 s12'>
    {{ ticket.ticketnumber }}
    </div>
</div>




</div>
   

{{ entries }}
<button class="btn waves-effect waves-light" type="submit">Submit
<i class="material-icons right">send</i>
</button>
</form>




<script>
    
    $('select').formSelect();
    

    $('#id_startdate').datepicker({
        format: 'yyyy-mm-dd'
    });
    $('#id_enddate').datepicker({
        format: 'yyyy-mm-dd'
    });
    $('#id_ticketstartdate').datepicker({
        format: 'yyyy-mm-dd',
        onClose: function(){
            var date = $('#id_ticketstartdate').val();
            $('#id_ticketstartdate').datepicker('destroy');
            $('#id_ticketstartdate').timepicker();
            $('#id_ticketstartdate').timepicker('open');
            $('#id_ticketstartdate').focusout(function(){
                var time = $('#id_ticketstartdate').val();
                $('#id_ticketstartdate').html(date+' '+time);
                
            });

        },
        });

    $('#id_clientid').change(function(event){
        if($("#hotness").children().length) {
          $("#hotness").empty();
            ajaxEmail();
        } else {
            ajaxEmail();
        }
    });
        function ajaxEmail () {    
        var urls = $('#ajax_url').attr('href');
        var  clientid = $('#id_clientid');
        $.ajax({
            type: "POST",
            dataType: "json",
            url: urls,
            data: {
                'clientid' : $('#id_clientid').val(), csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(result) {
                $.each(result, function(index, value) {
                    $('#id_contact_name')
                        .append($("<option></option>")
                                .attr("value",value.fields.contactname)
                                .text(value.fields.contactname));

                });
        $('#id_contact_name').formSelect();




                $.each(result, function(index, value){
                    if($('.input'))
                    if (value.fields.sendticketcompleteemail == true) {
                        $('#hotness').append($('<p></p>')).append($('<label></label>').attr('for', value.fields.emailaddress)).append($('<input />').attr('type','checkbox')).append($('<span></span>').text(value.fields.contactname))                     
                    };
                     
                })


            },
        
            error: function (error) {
                alert("Error with Ajax, You SUCK");
            }
        });
    };

</script>
{% endblock %}

 

crm_app/templates/crm_temps/forms/new-entry.html
{% extends 'base.html' %} 
{% block title %}
<h3>New Time Entry</h3>
{% endblock %} 
{% block body %}

{% block entry-form %}
{% include 'crm_temps/forms/entry-form.html' %}
{% endblock %}


{% endblock %}

crm_app/templates/crm_temps/forms/new-ticket.html
{% include 'crm_temps/forms/multi-page-new-ticket.html' %}


<a id="ajax_url" href="{% url 'crm:ajax_req' %}"></a>


<style>
/* label focus color */
 .input-field input:focus + label {
   color: red !important;

 }
input:not([type]), input[type=text]:not(.browser-default), input[type=password]:not(.browser-default), input[type=email]:not(.browser-default), input[type=url]:not(.browser-default), input[type=time]:not(.browser-default), input[type=date]:not(.browser-default), input[type=datetime]:not(.browser-default), input[type=datetime-local]:not(.browser-default), input[type=tel]:not(.browser-default), input[type=number]:not(.browser-default), input[type=search]:not(.browser-default), textarea.materialize-textarea {
    background-color: lightgrey;
 }
 </style>

<script>
    $("[name='#id_enddate']").focusout(function(){
        var sd = new Date($('#id_startdate').val());
        var ed = new Date($('#id_enddate').val());
        var time = (ed - sd)/1000;
        $('#id_time_spent_minutes_field').attr("value", time);        
    });
    $(document).ready(function(){
    $('select').formSelect();
    $('datepicker').datepicker();
  });
</script>